### ISSUE TITLE
Port SAPCAR layer to be Python 2/3 compatible

### ISSUE THREAD

**Issue by okuuva** [CoreSecurity/pysap#27]
Continuing Python2/3 project by porting SAPCAR layer and related unit tests. Depends on #25 (resolved in #26).

@martingalloar penny for your thoughts: should we handle all the incoming and outgoing strings (like file names, versions and such)  as unicode? That would be more user friendly and more Pythonic but would require some `.encode()` and `.decode()` calls here and there as they must be stored as byte strings in the archive files. Then again, there's nothing new about that when handling binary data with Python 3...

**Comment by martingalloar** [comment]
Looking good on my side, closed with #28!
As for the handling of strings/bytes, agree with the approach you took on #28. For some other layers or protocols we might want to define if this same approach is the preferred, but as you said, there's no much choice if trying to follow Python 3.
