### ISSUE TITLE
Port pysapcar tool to be Python 2/3 compatible

### ISSUE THREAD

**Issue by okuuva** [CoreSecurity/pysap#29]
Continuing Python2/3 project with pysapcar cli tool.

**Comment by okuuva** [comment]
Status update: I was on vacation last week and been busy with other stuff this week so no much progress. Tested it a bit though and seems that it's already compatible, but since there's no unit tests it's hard to say for sure. I'm working on adding some to ensure the compatibility, but that means I have to refactor it quite a bit in order to be able to make it testable.

**Comment by martingalloar** [comment]
Hey! Same here, over some days off so reduced availability. I think you're right and it make sense. I don't think we should add unit tests for example scripts, as they are just examples, but in the case of `pysapcar` and `pysapgenpse` I wanted to keep some basic functionality to be somehow stable so it would be great to have those covered with unit tests.
Added https://github.com/CoreSecurity/pysap/projects/1#card-11495772 and https://github.com/CoreSecurity/pysap/projects/1#card-11495777 to track those!
