### ISSUE TITLE
Interacting with SAP GUI

### ISSUE THREAD

**Issue by Tset-Noitamotua** [CoreSecurity/pysap#9]
Hi! Somewhere in your docs I've read that pysap can be used to interact with SAP GUI.

Can you provide an example how to achieve that?

Cheers
Tset

**Comment by vah13** [comment]
Hi, are you mean what you want use pysap instead SAP GUI?

**Comment by Tset-Noitamotua** [comment]
@vah13 No, actually my question goes towards 'is it possible to control SAP GUI programatically with pysap?'

But if you know how to interact / to control SAP with pysap (or something else) instead of SAP GUI I would like to know that, too.

**Comment by martingalloar** [comment]
Hi! The library implements some messages of the SAP Diag protocol, so it's possible to programatically interact with a SAP server, in the same way the SAP GUI does. But it's not possible to control SAP GUI, I think [scripting](https://archive.sap.com/documents/docs/DOC-8971) can be probably used for that.

In the example folders there are several scripts that ilustrate the way SAP Diag protocol can be used:
- you can render a dialog page, such as the [login screen](https://github.com/CoreSecurity/pysap/blob/master/examples/diag_render_login_screen.py).
- you [can grab](https://github.com/CoreSecurity/pysap/blob/master/examples/diag_login_screen_info.py) info from the login screen.
- you can perform a MITM to [intercept ](https://github.com/CoreSecurity/pysap/blob/master/examples/diag_interceptor.py) login passwords or [recover](https://github.com/CoreSecurity/pysap/blob/master/examples/diag_capturer.py) them from the network or a pcap.
- [..]

It's there something specific you want to achieve?

**Comment by Tset-Noitamotua** [comment]
You say
>  The library implements some messages of the SAP Diag protocol, so it's possible to programmatically interact with a SAP server, **in the same way the SAP GUI does**. 

Does that mean that with pysap I could do programmatically almost everything what a user can do through SAP GUI? 

I just wondered if pysap could be utilized for test automation purposes. I am more interested in quality assurance especially in test automation less in security aspects.  I encounter some limits then automating tests by calling BAPIs (RFC) because not all BAPIs are remote enabled, further some SAP GUI actions (e.g. "Confirmation of Picking" in sales order & delivery context) are not backed by BAPIs at all and some BAPIs (e.g. BAPI_BILLINGDOC_CREATE) internally call a transaction (e.g. TCODE: VF01) thus can't be used through RFC.

**Comment by martingalloar** [comment]
> Does that mean that with pysap I could do programmatically almost everything what a user can do through SAP GUI?

Yes, with some caveats:
- not all messages of the Diag protocol are implemented;
- some transactions and operations with the Diag protocol carry embedded RFC calls, and the RFC protocol is not implemented in pysap.

As both of the protocols are proprietary and not publicly documented, there's still some work to be done to reach the level of interaction that something like what you want might need. But it's completelly doable.

From the protocol side, adding messages and fields is not difficult if you know them and have network/application traces and/or network captures. On the implementation side, maybe working in some event-driven framework (e.g. Twisted) might help.

**Comment by Tset-Noitamotua** [comment]
Are you aware of [PyRFC](https://github.com/SAP/PyRFC)?

>The pyrfc Python package provides Python bindings for SAP NetWeaver RFC Library, for a comfortable way of calling ABAP modules from Python and Python modules from ABAP, via SAP Remote Function Call (RFC) protocol. 

That does the RFC (remote enabled BAPI) part for me. Next I would like to have something as a fallback in case a transaction has no correspoding BAPI or only has a BAPI which is not remote enabled. Thus I could automate anything without the need to change something on SAP side.

Can you provide some links (for further reading) about Diag protocol, fields and messages and how to get network/application traces/captures so that I can try some things out?

**Comment by martingalloar** [comment]
> Are you aware of PyRFC?

Yes, and it's a very good project indeed! However, the goals are quite different: the PyRFC library uses SAP's RFC SDK, so it's not suitable for some scenarios pysap was aimed to (for example, a penetration tester that found out an SAP system and doesn't have a copy of the SDK available). Moreover, I'm not sure if it's possible to perform embedded RFC calls using PyRFC, as the dialect is different. It would be worth checking anyway.

> Can you provide some links (for further reading) about Diag protocol, fields and messages and how to get network/application traces/captures so that I can try some things out?

I think you can start with some of the [references](https://pysap.readthedocs.io/en/latest/user/user.html#references) in the doc, and maybe the talks at [Brucon](https://www.youtube.com/watch?v=p1jPUVKhvCo) and [Troopers](https://www.youtube.com/watch?v=fg8sMMHHZME). For capturing traffic, you can use [Wireshark](https://www.wireshark.org/) with pysap's brother project: the [wireshark plugin for SAP protocols](https://github.com/CoreSecurity/SAP-Dissection-plug-in-for-Wireshark).

**Comment by Tset-Noitamotua** [comment]
Great! Thank you, I'll check that out.

Cheers
Tset

**Comment by martingalloar** [comment]
Your welcome! Any improvement idea, new packet, or whatever feedback is welcomed!
